# Generated by Django 3.2.4 on 2021-06-10 09:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('acc_no', models.IntegerField(primary_key=True, serialize=False)),
                ('acc_holder', models.CharField(max_length=200)),
                ('email_id', models.EmailField(max_length=254)),
                ('current_balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_transferred', models.IntegerField(default=0)),
                ('acc_no_of_reciever', models.IntegerField(default=0)),
                ('updated_balance_of_reciever', models.IntegerField(default=0)),
                ('updated_balance_of_sender', models.IntegerField(default=0)),
                ('sender_name', models.CharField(max_length=100)),
                ('reciever_name', models.CharField(max_length=100)),
                ('Date_and_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('acc_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.customer')),
            ],
        ),
    ]
